# Generated by Django 3.2 on 2024-11-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedVisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('visa_number', models.CharField(max_length=100)),
                ('reason_for_extension', models.TextField()),
                ('requested_extension_dates', models.DateField()),
                ('photo', models.ImageField(upload_to='extended_visa_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='PassportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='passport_photos/')),
                ('contact_number', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=50)),
                ('entry_type', models.CharField(max_length=50)),
                ('travel_dates', models.DateField()),
                ('photo', models.ImageField(upload_to='visa_photos/')),
                ('purpose_of_visit', models.TextField()),
            ],
        ),
    ]
